services:
  - type: web
    name: edumaster-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: PORT
        fromService:
          type: web
          name: edumaster-backend
          property: port
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DATABASE_NAME
        value: eduplanner
      - key: MAX_CONTENT_LENGTH
        value: "16777216"
      - key: UPLOAD_FOLDER
        value: uploaded_slides
      - key: CORS_ORIGINS
        value: "*"
      - key: SMTP_SERVER
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SENDER_EMAIL
        sync: false